version: "3.3"
services:
  db:
    container_name: db
    image: mysql:latest
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: akbar
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=root --password=akbar"]
      interval: 20s
      timeout: 20s
      retries: 5

  web:
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    build: .

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: always
